version: '3'
services:
  device1:
    image: device1
    build: ./apps/device1
    container_name: device1
    restart: always
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - .:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    environment:
      - DEVICE_ID=device1
      - DEVICE_CONNECTIONSTRING=${DEVICE1_CONNECTIONSTRING}
      - IOTHUB_NAME=iot-joboffline-dev
    # command: /bin/sh -c "while sleep 1000; do :; done"
  device2:
    image: device1
    build: ./apps/device1
    container_name: device2
    restart: always
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - .:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    environment:
      - DEVICE_ID=device2
      - DEVICE_CONNECTIONSTRING=${DEVICE2_CONNECTIONSTRING}
#      - DEVICE_CONNECTIONSTRING=HostName=iot-joboffline-dev.azure-devices.net;DeviceId=device2;SharedAccessKey=asdf
      - IOTHUB_NAME=iot-joboffline-dev
    # command: /bin/sh -c "while sleep 1000; do :; done"
  service-console:
    image: service-console
    build: ./apps/service-console
    container_name: service-console
    restart: always
    volumes:
      # Mounts the project folder to '/workspace'. While this file is in .devcontainer,
      # mounts are relative to the first file in the list, which is a level up.
      - .:/workspace:cached

    # Overrides default command so things don't shut down after the process ends.
    environment:
      - IOTHUBOWNER_SAS_KEY=${IOTHUBOWNER_SAS_KEY}
      - IOTHUB_NAME=${IOTHUB_NAME}
#      - IOTHUB_NAME=iot-joboffline-dev
#      IOTHUB_NAME
#      - TEST_VAR=${TEST_VAR}
      
    # command: /bin/sh -c "while sleep 1000; do :; done"
